---
- name: Student Convert Pipeline
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:

    - name: munendra.json convert karo
      uri:
        url: http://192.168.232.131:30007/convert
        method: POST
        body_format: json
        body:
          file: "munendra.json"
        status_code: 200
      ignore_errors: yes

    - name: priyanka.yaml convert karo
      uri:
        url: http://192.168.232.131:30007/convert
        method: POST
        body_format: json
        body:
          file: "priyanka.yaml"
        status_code: 200
      ignore_errors: yes

    - name: Complete
      debug:
        msg: "Dono files convert aur push ho gayi!"
