---
- name: JSON ↔ YAML Convert and Push
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    repo_url: https://rajputgagan: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@github.com/rajputgagan/Student.git
    repo_path: /tmp/myrepo
    git_branch: main

  tasks:

    - name: Install dependencies
      raw: apk add --no-cache python3 git py3-yaml
      changed_when: false
      failed_when: false

    - name: Remove old repo (if exists)
      file:
        path: "{{ repo_path }}"
        state: absent

    - name: Clone fresh repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ git_branch }}"
        force: yes

    - name: Set git username
      command: git config user.name "rajputgagan"
      args:
        chdir: "{{ repo_path }}"

    - name: Set git email
      command: git config user.email "gr9582730@gmail.com"
      args:
        chdir: "{{ repo_path }}"

    - name: Pull latest changes
      command: git pull --rebase origin {{ git_branch }}
      args:
        chdir: "{{ repo_path }}"

    - name: Convert JSON → YAML
      command: python3 convert.py json2yaml munendra.json output.yaml
      args:
        chdir: "{{ repo_path }}"

    - name: Convert YAML → JSON
      command: python3 convert.py yaml2json priyanka.yaml output.json
      args:
        chdir: "{{ repo_path }}"

    - name: Git add all files
      command: git add .
      args:
        chdir: "{{ repo_path }}"

    - name: Check if changes exist
      shell: git diff --cached --quiet
      args:
        chdir: "{{ repo_path }}"
      register: git_diff
      failed_when: false
      changed_when: false

    - name: Commit changes
      command: git commit -m "Auto convert JSON ↔ YAML via AWX"
      args:
        chdir: "{{ repo_path }}"
      when: git_diff.rc != 0

    - name: Push to GitHub
      command: git push origin {{ git_branch }}
      args:
        chdir: "{{ repo_path }}"
      when: git_diff.rc != 0

    - name: Done
      debug:
        msg: "✅ Conversion + Git Push successful!"
