---
- name: Convert files from GitHub and push back
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    repo_url: "git@github.com:rajputgagan/Student.git"
    repo_path: "/tmp/myrepo"
    venv_path: "/tmp/venv"
    git_branch: "main"
    github_username: "rajputgagan"
    github_email: "gr9582730@gmail.com"

  tasks:
    - name: Install required packages
      raw: apk add --no-cache python3 git py3-virtualenv openssh
      changed_when: false
      failed_when: false

    - name: Remove old repo
      file:
        path: "{{ repo_path }}"
        state: absent

    - name: Remove old venv
      file:
        path: "{{ venv_path }}"
        state: absent

    - name: Clone repo from GitHub using SSH
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ git_branch }}"
        force: yes
        accept_hostkey: yes

    - name: Set git username
      command: git config user.name "{{ github_username }}"
      args:
        chdir: "{{ repo_path }}"

    - name: Set git email
      command: git config user.email "{{ github_email }}"
      args:
        chdir: "{{ repo_path }}"

    - name: Pull latest changes from GitHub
      command: git pull --rebase origin {{ git_branch }}
      args:
        chdir: "{{ repo_path }}"

    - name: Create Python virtual environment
      command: python3 -m venv {{ venv_path }}

    - name: Install PyYAML
      command: "{{ venv_path }}/bin/pip install pyyaml"

    - name: Convert JSON to YAML
      command: >
        {{ venv_path }}/bin/python convert.py
        json2yaml
        munendra.json
        output.yaml
      args:
        chdir: "{{ repo_path }}"

    - name: Convert YAML to JSON
      command: >
        {{ venv_path }}/bin/python convert.py
        yaml2json
        priyanka.yaml
        output.json
      args:
        chdir: "{{ repo_path }}"

    - name: Add files to git
      command: git add .
      args:
        chdir: "{{ repo_path }}"

    - name: Check if there are staged changes
      shell: git diff --cached --quiet
      args:
        chdir: "{{ repo_path }}"
      register: git_diff
      failed_when: false
      changed_when: false

    - name: Commit changes
      command: git commit -m "Auto convert JSON and YAML via AWX"
      args:
        chdir: "{{ repo_path }}"
      when: git_diff.rc != 0

    - name: Push changes to GitHub
      command: git push origin {{ git_branch }}
      args:
        chdir: "{{ repo_path }}"
      when: git_diff.rc != 0

    - name: No changes found
      debug:
        msg: "No changes detected, nothing to commit or push."
      when: git_diff.rc == 0

    - name: Success
      debug:
        msg: "Conversion completed and changes pushed to GitHub."
